@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "markk351",
  "password": "peradetlic",
  "email": "test@test.com",
  "avatarColor": "blue",
  "avatarImage": ""
}

###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "markk351",
  "password": "peradetlic"
}
