@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post/comment
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo": "63d0ec191abc1dd5904ad297",
  "postId": "63d4edd27352934339809fdb",
  "comment": "This is comment. Hi there!",
  "profilePicture": "https://res.cloudinary.com/dt5lgaara/image/upload/v1673805407/63c43e5ebb8a1f5d2c752f2d"
}

###
GET {{baseUrl}}/{{urlPath}}/post/comments/:postId
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/comments/names/:postId
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/single/comment/:postId/:commentId
Content-Type: application/json
Accept: application/json
withCredentials: true
