@baseUrl = http://localhost:5000
@urlPath = api/v1

###
PUT {{baseUrl}}/{{urlPath}}/user/follow/63cecd537a01a246330a7ab8
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
PUT {{baseUrl}}/{{urlPath}}/user/unfollow/63cecd537a01a246330a7ab8/63cecd457a01a246330a7ab1
Content-Type: application/json
Accept: application/json
withCredentials: true

{}
